name: Build API

on:
  push:
    branches:
      - main
    paths:
      - api/**
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - api/**
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: nest-settings-api
  ACR_NAME: nestsettingsregistry
  ACR_REPOSITORY: nestsettings

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZ_ACR_USERNAME }}
          password: ${{ secrets.AZ_ACR_PASSWORD }}

      - name: 'Build Docker image and push to registry'
        run: |
          docker build api/ -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.ACR_REPOSITORY }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.ACR_REPOSITORY }}

      - name: 'Deploy Docker image to Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ env.ACR_NAME }}.azurecr.io/${{ env.ACR_REPOSITORY }}'
      
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Configuration'
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          app-settings-json: |
            [
              {
                "name": "DOCKER_REGISTRY_SERVER_URL",
                "value": "https://${{ env.ACR_NAME }}.azurecr.io",
                "slotSetting": false
              },
              {
                "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                "value": "${{ secrets.AZ_ACR_USERNAME }}",
                "slotSetting": false
              },
              {
                "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                "value": "${{ secrets.AZ_ACR_PASSWORD }}",
                "slotSetting": false
              },
              {
                "name": "DATABASE_USER",
                "value": "${{ secrets.AZ_DATABASE_USERNAME }}",
                "slotSetting": false
              },
              {
                "name": "DATABASE_PASSWORD",
                "value": "${{ secrets.AZ_DATABASE_PASSWORD }}",
                "slotSetting": false
              },
              {
                "name": "DATABASE_NAME",
                "value": "nest-settings",
                "slotSetting": false
              },
              {
                "name": "DATABASE_PORT",
                "value": "5432",
                "slotSetting": false
              },
              {
                "name": "DATABASE_HOST",
                "value": "pg-nest-settings.postgres.database.azure.com",
                "slotSetting": false
              },
              {
                "name": "WEBSITES_PORT",
                "value": "3000",
                "slotSetting": false
              }
            ]