on:
  workflow_dispatch:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: nest-settings

jobs:
  secrets:
    name: Get secrets test
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Configuration'
      uses: azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        app-settings-json: |
         [
             {
                 "name": "DB_NAME",
                 "value": "nest-settings",
                 "slotSetting": false
             },
             {
                 "name": "DB_USERNAME",
                 "value": "${{ secrets.AZ_DB_USER }}",
                 "slotSetting": false
             },
             {
                 "name": "DB_PASSWORD",
                 "value": "${{ secrets.AZ_DB_PASSWORD }}",
                 "slotSetting": false
             },
         ]
