on:
  workflow_dispatch:
    branches: [ main ]

env:
  AZ_CLI_VERSION: '2.30.0'
  AZ_LOCATION: 'australiaeast'
  AZ_RESOURCE_GROUP: 'rg-nest-settings'
  AZ_WEBAPP_NAME: 'nest-settings'
  AZ_DATABASE_NAME: 'pg-nest-settings'
  DATABASE_NAME: 'nest-settings'

jobs:
  create-resources:
    name: Create Azure resources
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      id: createdb
      with:
        azcliversion: ${{ env.AZ_CLI_VERSION }}
        inlineScript: |
          echo "::set-output name=DB::$(
            az postgres flexible-server create --location ${{ env.AZ_LOCATION }} --resource-group ${{ env.AZ_RESOURCE_GROUP }} \
            --name ${{ env.AZ_DATABASE_NAME }} --database-name ${{ env.DATABASE_NAME }}  \
            --sku-name Standard_B1ms --tier Burstable --public-access all --version 13 -o json
          )"
    - name: Get DB
      run: |
          echo "DB: ${{ steps.createdb.outputs.DB }}"
