on:
  workflow_dispatch:
    branches: [ main ]

env:
  AZ_CLI_VERSION: '2.30.0'
  AZ_LOCATION: 'australiaeast'
  AZ_RESOURCE_GROUP: 'rg-nest-settings'
  AZ_WEBAPP_NAME: 'nest-settings'
  AZ_DATABASE_NAME: 'pg-nest-settings'
  DATABASE_NAME: 'nest-settings'

jobs:
  create-resources:
    name: Create Azure resources
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      id: createdb
      with:
        azcliversion: ${{ env.AZ_CLI_VERSION }}
        inlineScript: |
          DB=$(az postgres flexible-server create --location ${{ env.AZ_LOCATION }} --resource-group ${{ env.AZ_RESOURCE_GROUP }} \
          --name ${{ env.AZ_DATABASE_NAME }} --database-name ${{ env.DATABASE_NAME }}  \
          --sku-name Standard_B1ms --tier Burstable --public-access all --version 13 -o json)
          USERNAME=$(echo $DB | jq '.username')
          echo "::set-output name=USERNAME::$USERNAME"
          PASSWORD=$(echo $DB | jq '.password')
          echo "::set-output name=PASSWORD::$PASSWORD"
# Example output
# {
#   "connectionString": "postgresql://nestadmin:xxxx@pg-nest-settings.postgres.database.azure.com/postgres?sslmode=require",
#   "databaseName": "nest-settings",
#   "firewallName": "AllowAll_2021-12-4_13-7-43",
#   "host": "pg-nest-settings.postgres.database.azure.com",
#   "id": "/subscriptions/c9d9b3ef-44e7-470e-bfce-7d0938297a3a/resourceGroups/rg-nest-settings/providers/Microsoft.DBforPostgreSQL/flexibleServers/pg-nest-settings",
#   "location": "Australia East",
#   "password": "xxxx",
#   "resourceGroup": "rg-nest-settings",
#   "skuname": "Standard_B1ms",
#   "username": "nestadmin",
#   "version": "13"
# }
    - name: '[Secret] store db username'
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'AZ_DB_USER'
        value: ${{ steps.createdb.outputs.USERNAME }}
        repository: ${{ github.repository }}
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: '[Secret] store db password'
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'AZ_DB_PASSWORD'
        value: ${{ steps.createdb.outputs.PASSWORD }}
        repository: ${{ github.repository }}
        token: ${{ secrets.ACCESS_TOKEN }}
