on:
  workflow_dispatch:
    branches: [ main ]

env:
  AZ_RESOURCE_GROUP: 'rg-nest-settings'

jobs:
  create-resources:
    name: Create Azure resources
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Provision resources
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZ_SUBSCRIPTION }}
        resourceGroupName: ${{ env.AZ_RESOURCE_GROUP }}
        template: bicep/provision.bicep
        parameters: databasePassword=${{ secrets.AZ_DATABASE_PASSWORD }} environmentName=production
