name: Provision Resources

on:
  workflow_dispatch:
    branches: [ main ]

env:
  AZ_RESOURCE_GROUP: 'rg-nest-settings'
  AZ_API_NAME: 'nest-settings-api'
  AZ_ACR_NAME: 'nestsettingsregistry'
  AZ_CLI_VERSION: '2.30.0'

jobs:
  create-resources:
    name: Create Azure resources
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Provision resources
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZ_SUBSCRIPTION }}
        resourceGroupName: ${{ env.AZ_RESOURCE_GROUP }}
        template: .bicep/provision.bicep
        parameters: databasePassword=${{ secrets.AZ_DATABASE_PASSWORD }}

    - name: Get API publishing profile
      id: get-profile
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZ_CLI_VERSION }}
        inlineScript: |
          profile=$(az webapp deployment list-publishing-profiles --resource-group ${{ env.AZ_RESOURCE_GROUP }} --name ${{ env.AZ_API_NAME }} --xml)
          echo "::add-mask::$profile"
          echo "::set-output name=profile::$profile"
    - name: Set Secret
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'AZURE_WEBAPP_PUBLISH_PROFILE'
        value: ${{ steps.get-profile.outputs.profile }}
        repository: ${{ github.repository }}
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Get ACR credentials
      id: get-acr
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZ_CLI_VERSION }}
        inlineScript: |
          creds=$(az acr credential show --resource-group ${{ env.AZ_RESOURCE_GROUP }} --name ${{ env.AZ_ACR_NAME }})
          creds="${creds//'%'/'%25'}"
          creds="${creds//$'\n'/'%0A'}"
          creds="${creds//$'\r'/'%0D'}"
          echo "::set-output name=creds::$creds"
    - name: Set Secret
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'AZ_ACR_USERNAME'
        value: ${{fromJson(steps.get-acr.outputs.creds).username}}
        repository: ${{ github.repository }}
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Set Secret
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'AZ_ACR_PASSWORD'
        value: ${{fromJson(steps.get-acr.outputs.creds).passwords[0].value}}
        repository: ${{ github.repository }}
        token: ${{ secrets.ACCESS_TOKEN }}        