name: Set Secrets

on:
  workflow_dispatch:
    branches: [ main ]

env:
  AZ_RESOURCE_GROUP: 'rg-nest-settings'
  AZ_API_NAME: 'nest-settings-api'
  AZ_ACR_NAME: 'nestsettingsregistry'
  AZ_CLI_VERSION: '2.30.0'

jobs:
  create-resources:
    name: Create Azure resources
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get API publishing profile
      id: get-profile
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZ_CLI_VERSION }}
        inlineScript: |
          echo "::set-output name=profile::add-mask::$(az webapp deployment list-publishing-profiles --resource-group ${{ env.AZ_RESOURCE_GROUP }} --name ${{ env.AZ_API_NAME }} --xml)"
    - name: Set Secret
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'AZURE_WEBAPP_PUBLISH_PROFILE'
        value: '${{ steps.get-profile.outputs.profile }}'
        repository: ${{ github.repository }}
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Get ACR credentials
      id: get-acr
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZ_CLI_VERSION }}
        inlineScript: |
          echo "::set-output name=username::add-mask::$(az acr credential show --resource-group ${{ env.AZ_RESOURCE_GROUP }} --name ${{ env.AZ_ACR_NAME }} --query username)"
          echo "::set-output name=password::add-mask::$(az acr credential show --resource-group ${{ env.AZ_RESOURCE_GROUP }} --name ${{ env.AZ_ACR_NAME }} --query passwords[0].value)"
    - name: Set Secret
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'AZ_ACR_USERNAME'
        value: '${{ ::add-mask::steps.get-acr.outputs.username }}'
        repository: ${{ github.repository }}
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Set Secret
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'AZ_ACR_PASSWORD'
        value: '${{ ::add-mask::steps.get-acr.outputs.password }}'
        repository: ${{ github.repository }}
        token: ${{ ::add-mask::secrets.ACCESS_TOKEN }}        